name: Build
on: 
    push:
        branches:
            - main
jobs:
    build:
        runs-on: windows-lates
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install deps
              run: npm i
            - name: Build
              run: npm run build