name: Build
on: 
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install deps
              run: npm ci
            - name: Build
              run: npm run build
            - uses: EndBug/add-and-commit@v9